"""
Market Research Agent - Streamlit Web App
==========================================
A web interface for the AI Market Research Agent.
Users enter a company name and competitors, then get a
professional PowerPoint report generated by AI agents.
"""

import os
import io
import time
import tempfile
from datetime import datetime

import streamlit as st
from dotenv import load_dotenv


# ── Page Config ──────────────────────────────────────────
st.set_page_config(
    page_title="AI Market Research Agent",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Custom CSS ───────────────────────────────────────────
st.markdown("""
<style>
    /* Dark theme overrides */
    .stApp {
        background: linear-gradient(135deg, #0F1A30 0%, #1B2A4A 100%);
    }
    .main-header {
        text-align: center;
        padding: 2rem 0 1rem 0;
    }
    .main-header h1 {
        color: #3498DB;
        font-size: 2.5rem;
        font-weight: 700;
    }
    .main-header p {
        color: #BDC3C7;
        font-size: 1.1rem;
    }
    .agent-card {
        background: rgba(21, 36, 62, 0.8);
        border-radius: 12px;
        padding: 1.2rem;
        border-left: 4px solid #3498DB;
        margin-bottom: 0.8rem;
    }
    .agent-card h4 {
        color: #3498DB;
        margin: 0 0 0.3rem 0;
    }
    .agent-card p {
        color: #BDC3C7;
        margin: 0;
        font-size: 0.9rem;
    }
    .status-box {
        background: rgba(21, 36, 62, 0.8);
        border-radius: 12px;
        padding: 1.5rem;
        border: 1px solid #2C3E50;
    }
    div[data-testid="stForm"] {
        background: rgba(21, 36, 62, 0.6);
        border-radius: 12px;
        padding: 1.5rem;
        border: 1px solid #2C3E50;
    }
</style>
""", unsafe_allow_html=True)


def run_research(company: str, competitors: list[str], progress_placeholder):
    """Run the CrewAI research pipeline and return results."""
    # Load .env file (for local runs)
    load_dotenv()

    # Set up environment for Streamlit Cloud (secrets → env vars)
    try:
        for key in ["GROQ_API_KEY", "GEMINI_API_KEY", "SERPER_API_KEY", "MODEL_NAME", "OPENAI_API_KEY"]:
            if key in st.secrets:
                os.environ[key] = st.secrets[key]
    except Exception:
        pass  # No secrets configured (local mode uses .env)

    # Default to Groq if no model specified
    if not os.getenv("MODEL_NAME"):
        os.environ["MODEL_NAME"] = "groq/llama-3.3-70b-versatile"

    progress_placeholder.info("🔧 Initializing AI agents...")

    from src.crew import MarketResearchCrew

    crew = MarketResearchCrew()

    progress_placeholder.info("🔍 **Scout Agent** is researching competitors...")

    result = crew.run(company=company, competitors=competitors)
    report_text = str(result)

    return report_text


def generate_pptx_bytes(report_text: str, company: str, competitors: list[str],
                        theme: str = "classic_green", style: str = "consulting") -> bytes:
    """Generate PPTX and return as bytes for download."""
    from src.tools.ppt_generator import generate_pptx

    with tempfile.NamedTemporaryFile(suffix=".pptx", delete=False) as tmp:
        tmp_path = tmp.name

    generate_pptx(report_text, company, competitors, tmp_path,
                  theme=theme, style=style)

    with open(tmp_path, "rb") as f:
        pptx_bytes = f.read()

    os.unlink(tmp_path)
    return pptx_bytes


# ── Header ───────────────────────────────────────────────
st.markdown("""
<div class="main-header">
    <h1>📊 AI Market Research Agent</h1>
    <p>Multi-agent intelligence system that researches your competitors<br>
    and generates professional PowerPoint reports</p>
</div>
""", unsafe_allow_html=True)

# ── How it works ─────────────────────────────────────────
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("""
    <div class="agent-card">
        <h4>🔍 Scout Agent</h4>
        <p>Gathers competitive intelligence and researches each competitor's products, pricing, and positioning</p>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown("""
    <div class="agent-card">
        <h4>📈 Analyst Agent</h4>
        <p>Performs SWOT analysis, identifies market gaps, and ranks threats and opportunities</p>
    </div>
    """, unsafe_allow_html=True)

with col3:
    st.markdown("""
    <div class="agent-card">
        <h4>📝 Reporter Agent</h4>
        <p>Creates a professional report with executive summary, competitive matrix, and strategy</p>
    </div>
    """, unsafe_allow_html=True)

st.markdown("---")

# ── Input Form ───────────────────────────────────────────
with st.form("research_form"):
    st.subheader("Enter Research Details")

    company = st.text_input(
        "Your Company / Business Name",
        placeholder="e.g., My AI Automation Agency",
    )

    competitors_input = st.text_input(
        "Competitors (comma-separated)",
        placeholder="e.g., Zapier, Make.com, n8n",
    )

    st.caption("💡 Tip: Start with 1-2 competitors for faster results. More competitors = longer processing time.")

    # Presentation options
    st.markdown("#### Presentation Options")
    opt_col1, opt_col2 = st.columns(2)
    with opt_col1:
        theme_display = st.selectbox(
            "Color Theme",
            ["Classic Green", "Navy Blue", "Charcoal"],
            help="Choose the color palette for your PowerPoint deck",
        )
    with opt_col2:
        style_display = st.selectbox(
            "Template Style",
            ["Consulting", "Corporate", "Minimal"],
            help="Choose the layout style for your slides",
        )

    submitted = st.form_submit_button("🚀 Generate Report", use_container_width=True)

# ── Run Research ─────────────────────────────────────────
if submitted:
    # Map display names → internal keys
    theme_key = {"Classic Green": "classic_green", "Navy Blue": "navy_blue", "Charcoal": "charcoal"}[theme_display]
    style_key = {"Consulting": "consulting", "Corporate": "corporate", "Minimal": "minimal"}[style_display]

    if not company.strip():
        st.error("Please enter a company name.")
    elif not competitors_input.strip():
        st.error("Please enter at least one competitor.")
    else:
        competitors = [c.strip() for c in competitors_input.split(",") if c.strip()]

        st.markdown("---")
        st.subheader("Research in Progress")

        # Progress tracking
        progress_bar = st.progress(0)
        status = st.empty()

        # Agent status cards
        agent_col1, agent_col2, agent_col3 = st.columns(3)

        try:
            # Phase 1: Scout
            with agent_col1:
                scout_status = st.empty()
                scout_status.info("🔍 **Scout**: Researching...")
            progress_bar.progress(10)
            status.info(f"Researching {len(competitors)} competitors: {', '.join(competitors)}")

            # Run the full pipeline
            report_text = run_research(company, competitors, status)

            # Update progress
            with agent_col1:
                scout_status.success("🔍 **Scout**: Complete!")
            progress_bar.progress(40)

            with agent_col2:
                agent_col2.success("📈 **Analyst**: Complete!")
            progress_bar.progress(70)

            with agent_col3:
                agent_col3.success("📝 **Reporter**: Complete!")
            progress_bar.progress(85)

            # Phase 2: Generate PPT
            status.info("📊 Generating PowerPoint presentation...")
            pptx_bytes = generate_pptx_bytes(report_text, company, competitors,
                                               theme=theme_key, style=style_key)
            progress_bar.progress(100)

            status.success("✅ Research complete! Your report is ready.")

            # ── Results ──────────────────────────────────────
            st.markdown("---")
            st.subheader("Your Report")

            # Download buttons
            dl_col1, dl_col2 = st.columns(2)
            with dl_col1:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                safe_name = company.lower().replace(" ", "_")
                st.download_button(
                    label="📥 Download PowerPoint (.pptx)",
                    data=pptx_bytes,
                    file_name=f"report_{safe_name}_{timestamp}.pptx",
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    use_container_width=True,
                )

            with dl_col2:
                st.download_button(
                    label="📥 Download Markdown (.md)",
                    data=report_text,
                    file_name=f"report_{safe_name}_{timestamp}.md",
                    mime="text/markdown",
                    use_container_width=True,
                )

            # Show report preview
            with st.expander("📄 Preview Report", expanded=True):
                st.markdown(report_text)

        except Exception as e:
            progress_bar.progress(0)
            status.error(f"An error occurred: {str(e)}")
            st.error(
                "Something went wrong during the research process. "
                "This could be due to API rate limits. Please try again in a minute."
            )
            with st.expander("Error Details"):
                st.code(str(e))

# ── Footer ───────────────────────────────────────────────
st.markdown("---")
st.markdown(
    "<p style='text-align: center; color: #7F8C8D; font-size: 0.85rem;'>"
    "Powered by CrewAI + Groq | Built with Streamlit"
    "</p>",
    unsafe_allow_html=True,
)
